### ISSUE TITLE
¿Cómo buscar por tuits que contengan dos (o más) palabras?

### ISSUE THREAD

**Issue by numeroteca** [congosto/t-hoarder#5]
A la hora de rellenar el archivo words.txt ¿cómo se buscaría por tuits que contengan las palabras "correa" y "declaración"?

**Comment by congosto** [comment]
He añadido estos párrafos a a la arquitectura de T-hoarder

Esta API streaming permite obtener los tuits mediante filtrado o por muestra aleatoria. El filtrado se puede realizar por una de estas tres formas:

1. **Por palabras clave**: se obtienen los tuits que se ajustan a un patrón de búsqueda proporcionando una lista de palabras o expresiones separadas por comas. Las expresiones son palabras separadas por espacios que si se encuentran en el mensaje, independientemente del orden en que aparezcan, cumplen la condición. Las comas que separan las palabras o expresiones actúan como el operador lógico OR y en una expresión los espacios que separan las palabras se comportan como el conector lógico AND. Por ejemplo, la búsqueda “#metromadrid, metro Madrid” proporcionaría los tuits que contengan “#metromadrid” OR (“metro” AND “Madrid”).

2. **Por usuarios**: se adquieren los tuits de los usuarios suministrados mediante una lista con sus identificadores separados por comas. También se obtienen todas las reacciones a estos mensajes, bien sean retransmisiones (RTs) automáticas o manuales, menciones, citas o respuestas.

3. **Por geolocalización**: se reciben los tuits publicados desde una o varias zonas geográficas rectangulares, cada una de ellas delimitada por una coordenada superior este y otra inferior oeste. Con esta opción sólo se recogen mensajes geolocalizados.

Estas tres opciones son excluyentes, no es factible buscar por más de una opción a la vez. Cuando es necesario monitorizar por usuarios y por palabras clave, la única solución es capturar dos flujos de datos en paralelo para luego fusionarlos eliminando los mensajes duplicados. Este caso es muy frecuente en el seguimiento de campañas electorales en las que es interesante conocer la conversación en torno a los candidatos (usuarios) y los lemas de la campaña (lista de palabras clave).

**Comment by numeroteca** [comment]
Creo que queda clarísimo. +1 a incorporar esto a la wiki.
